--select*from restaurant where r_name like '%기%';
create table restaurant (
          r_name varchar2(30) not null,
          type varchar2(30) not null,
          location varchar2(150) not null,
          best_yn char(1) default 'N',
          grade number default 3,
          description varchar2(3000),
          category varchar2(50),
          r_phone varchar2(30),
          parking_yn char(1) default 'N',
          open_time number,
          close_time number,
          holiday varchar2(30),
          
          constraint pk_restaurant_r_name primary key (r_name),
          constraint ck_restaurant_best check (best_yn in ('Y','N')),
          constraint ck_restaurant_grade check (grade between 0 and 5),
          constraint ck_restaurant_parking check (parking_yn in ('Y','N')),
          constraint ck_restaurant_open check (open_time between 0 and 2400),
          constraint ck_restaurant_close check (close_time between 0 and 2400)
);

--drop table restaurant;

-- 구디(정영균)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('낭만부대찌개','한식','서울시 구로구 구로동','N','4','점심엔 부대찌개, 특재 마늘 소스와 저렴한 가격으로 즐길 수 있는 부대찌개 맛집','탕,찌개,전골','02-839-8090','N',1100,2200,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('춘자싸롱','한식','서울시 구로구 구로동','N','3.9','육회와 육전 맛집. 시끌시끌한 분위기의 가볼만한 맛집!','한정식,백반,정통한식','02-869-4873','N',1500,300,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('구로곱창','한식','서울시 관악구 신림동','N','3.7','가성비 맛집! 구로구 곱창 원탑!','고기요리','02-839-7848','N',1700,2250,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('한판소갈비','한식','서울시 구로구 구로동','N','3','숯불에 구운 맛있는 소갈비와 최고의 소고기 육개장','고기요리','02-869-7048','N',1130,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('한우마당','한식','서울시 관악구 신림동','N','3','소고기의 고급진 맛을 느낄 수 있는 맛집! 직원이 직접 구워주는 편리함!','고기요리','02-867-0070','Y',1200,2230,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('경식이네','한식','서울시 구로구 구로동','N','3','8년의 노하우! 삼치구이가 일품인 맛집!','전통주점,포차','070-4082-9321','N',1700,400,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('최우영스시','일식','서울시 구로구 구로동','N','3.6','구디단에서 가볍게 즐길 수 있는 스시맛집!','회,스시','02-2082-3430','N',1130,2130,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시메이진','일식','서울시 구로구 구로동','N','3.4','평일런치, 평일디너 뷔페식으로 즐길 수 있는 초밥 맛집!','회,스시','02-6344-3782','Y',1130,2200,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('멘무샤(구로)','일식','서울시 구로구 구로동','N','3','간단히 즐길 수 있는 일본 면요리 전문점!','라멘,소바,우동','02-2082-3228','N',1000,2300,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('박용석스시','일식','서울시 구로구 구로동','N','3','직장인들을 위한 점심맛집!','회,스시','02.2025.0003','N',1100,600,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('상운참치','일식','서울시 관악구 신림동','N','3','참치가 먹고싶다면 상운참치!','회,스시','02-869-1239','N',1130,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시비쇼쿠','일식','서울시 구로구 구로동','N','3','런치는 가성비의 제왕, 오마카세를 저렴하게 맛있게 즐길 수 있는 맛집','회,스시','02-869-1488','N',1130,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('르사이공','중식','서울시 구로구 구로동','N','3','다양한 베트남 음식을 즐길수있는 맛집!','베트남 음식','02-6344-3770','N',1100,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('호면가중경소면','중식','서울시 구로구 구로동','N','3','저렴하게 즐길 수 있는 혼밥 맛집!','기타 중식','02-869-6089','N',1030,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('홍콩반점0410','중식','서울시 구로구 구로동','N','3','24시간 즐길 수 있는 짬뽕 맛집!','정통 중식,일반 중식','02-869-3200','N',0,2400,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('손오공마라탕','중식','서울시 구로구 구로동','N','3','화끈한 맛을 느끼고 싶다면! 손오공 마라탕!','기타 중식','02-838-7788','N',1030,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('경성양꼬치','중식','서울시 구로구 구로동','N','3','자극적이지 않은 한국인의 입맛에 딱 맞는 양꼬치','기타 중식','02-851-3060','N',1400,200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('일심양꼬치','중식','서울시 구로구 구로동','N','3','친절한 사장님과 푸짐한 양꼬치!','기타 중식','02-864-9455','N',1700,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('라마노피자','양식','서울시 구로구 구로동','N','3','부담스럽지 않은 느끼함. 맥주가 맛있는 집!','기타양식','02-866-2828','N',1100,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('보나베띠','양식','서울시 구로구 구로동','N','3','피자, 파스타 맛집! 이탈리안 음식 전문점!','이탈리안','02-6344-3933','N',1130,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('베나레스','양식','서울시 구로구 구로동','N','3','강하지 않은 향신료. 누구나 즐길 수 있는 커리 맛집','인도 음식','02-863-9982','Y',1100,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('헤비스테이크','양식','서울시 구로구 구로동','N','3','저렴한 가격에 스테이크를 즐기고 싶다면, 헤비스테이크!','스테이크,바비큐','02-3283-3355','Y',1100,2130,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스윗밸런스','양식','서울시 구로구 구로동','N','3','건강해지는 맛. 샐러드가 맛있는 맛집!','기타 양식','02.866-3222','N',730,1930,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('샐러디','양식','서울시 구로구 구로동','N','3','건강식을 부담 없는 가격에 간편하고 빠르게 제공해주는 캐주얼 샐러드 전문점','기타 양식','02-839-9553','N',800,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('메이비','디저트','서울시 구로구 구로동','N','3.3','구로구의 힙플레이스, 주차가능한 브런치 맛집','브런치,버거,샌드위치','02-859-3073','N',830,2330,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('레더라','디저트','서울시 구로구 구로동','N','3','달달한 것이 땡긴다면! 초콜릿이 맛있는 레더라','카페,디저트','02-6344-3905','N',1100,2000,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('폴바셋','디저트','서울시 구로구 구로동','N','3','아이스크림이 맛있어 아이스크림 종류 음료가 모두 맛있는 디저트카페','카페,디저트','02-6344-3788','N',700,2200,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('설빙(구로구)','디저트','서울시 구로구 구로동','N','3','여름 더위를 시원하게 날릴 수 있는 빙수 맛집!','카페,디저트','02-6344-3959','N',1100,2300,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('투닷츠','디저트','서울시 구로구 구로동','N','3','분위기 좋은 카페 베이커리','베이커리','02-6951-4422','N',700,2300,'없음');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('곰미커피','디저트','서울시 구로구 구로동','N','3','수제 디저트 전문점','카페,디저트','010-7137-7710','N',1030,2130,'없음');

--성수동(전희진)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('텐동식당','일식','서울시 성동구 성수동2가 315-29','N','3','신선한 재료로 바삭하게 튀겨낸 튀김을 푸짐하게 올려내는 텐동 전문점 텐동식당','돈부리,일본카레,벤토','02-6339-0309','N',1100,2100,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('핑거팁스','양식','서울시 성동구 성수동2가 315-36','N','3.3','빵 만들고, 고기 갈고, 치즈 써는 버거집','브런치,버거,샌드위치','070-4232-0805','N',1100,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('성수족발','한식','서울시 성동구 성수동2가 289-273','N','3.4','부연설명 필요없는 성수 대표족발','족발,순대국','02-464-0425','N',1200,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('자그마치','디저트','서울시 성동구 성수동2가 317-12','N','3','레몬케이크가 맛있는 성수동 카페','카페,디저트','070-4409-7700','N',1100,2300,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('TBD','양식','서울시 성동구 성수동1가 16-22','N','3.5','남녀 누구나 부담없이 가기 좋은 내추럴 와인 바','브런치,버거,샌드위치','02-465-3334','Y',1200,2400,'월');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('다로베','양식','서울시 성동구 성수동1가 668-3','N','4.0','나폴리 정통 피자 문화를 전파하는 피제리아','이탈리안','02-499-3666','Y',1200,2200,'월');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('팩피','양식','서울시 성동구 성수동1가 656-947','N','3.1','Freaking Awesome Good PASTA','기타 양식','02-6052-7595','Y',1130,2200,'월');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('보이어','양식','서울시 성동구 성수동1가 16-26','N','3.2','Brunch and Wine Restaurant','기타 양식','070-4369-5994','N',1200,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('청죽골식당','한식','서울시 성동구 성수동1가 668-32','N','3.3','전남 담양에서 자라는 대나무의 잎으로 국내산 돼지고기를 숙성시킨 댓잎 왕 돼지갈비 전문점','고기요리','02-497-3980','N',1130,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('소문난성수감자탕','한식','서울시 성동구 성수동2가 315-100','N','3.4','성수역 4번출구 성수동 소문난 감자탕','탕,찌개,전골','02-465-6580','Y',0000,2400,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('밀도','디저트','서울시 성동구 성수동1가 656-442','N','2.9','밀도 빵집 성수동 서울숲 귀여운 큐브식빵','베이커리','02-497-5050','N',1100,1900,'월');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('라멘오야지','일식','서울시 성동구 성수동1가 668-41','N','3.9','라멘과 마제소바가 맛있는 성수동 맛집','라멘,소바,우동','010-2662-7960','N',1130,2100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('버섯집','한식','서울시 성동구 성수동1가 668-34','N','3.3','매일매일 신선한 재료들로 정성들여 요리하는 버섯집','탕,찌개,전골','02-3409-8887','N',1100,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('뺑드에코','디저트','서울시 성동구 성수동1가 656-569','N','3.3','건강까지 배려한 궁극의 빵','베이커리','02-462-4730','N',1030,2030,'월,화');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('할머니의레시피','한식','서울시 성동구 성수동1가 668-7','N','4.2','예쁘고 분위기도 정갈한 성수동 한식 맛집','한정식,백반,정통한식','02-467-5101','N',1130,2200,'화');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('아꼬떼뒤파르크','디저트','서울시 성동구 성수동1가 685-477','N','4.0','프랑스식 빵 전문점 아꼬떼 뒤 파르크','카페,디저트','070-4118-2009','N',1000,2000,'월,화');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('호호식당','일식','서울시 성동구 성수동1가 668-22','N','3.3','사랑하는 사람들과 특별한 시간을 보낼 수 있는 곳','정통일식,일반일식','02-498-2384','N',1100,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('웨이하이','중식','서울시 성동구 성수동2가 301-18','N','3.1','소소한모임또는 단체회식 자리가충분히 갖춰진 고급적인 분위기의 레스토랑','정통중식,일반중식','02-6053-7553','N',1130,2400,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('차이나플레인','중식','서울시 성동구 성수동2가 300-1','N','3.0','가족모임, 회식하기 좋은 성수동 중국집 "차이나플레인"','정통중식,일반중식','02-2205-2477','Y',1130,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('백정돈공장','한식','서울시 성동구 성수동2가 310-1','N','4.3','통삼겹살 맛집 백정 돈공장','고기요리','02-462-8295','N',1700,2400,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('어니언','디저트','서울시 성동구 성수동2가 277-135','N','3.0','명란 바게트와 팡도르가 맛있는 베이커리 카페','카페,디저트','02-1644-1941','N',800,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('소바식당','일식','서울시 성동구 성수동2가 315-49','N','3','현지보다 맛있는 성수동 일식 소바','라멘,소바,우동','02-6339-1552','N',1100,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('미즈라','일식','서울시 성동구 성수동2가 289-39','N','3','낯선곳에서 만난 이자카야 맛집','이자카야,오뎅,꼬치','02-6223-1072','Y',1800,130,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('달아래면','일식','서울시 성동구 성수동2가 321-89','N','3.3','탄탄면이 맛있는 성수역 라멘 맛집','라멘,소바,우동','02-464-9485','N',1130,2130,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('플레이스비브','양식','서울시 성동구 성수동2가 289-332','N','3.1','이것저것 다되는 즐거운 문화공간','이탈리안','070-8845-7382','Y',1100,2300,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('poze','디저트','서울시 성동구 성수동2가 315-41','N','3.2','예술가 아지트를 기반으로 한 카페 공간','카페,디저트','070-8830-5994','N',1000,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('일일향','중식','서울시 성동구 성수동2가 315-74','N','3.3','전통 중국요리전문점 일일향','정통중식,일반중식','02-462-2777','Y',1130,2130,'명절당일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('wei','중식','서울시 성동구 성수동1가 685-696','N','3','서울숲 갤러리아포레 중식당 웨이','정통중식,일반중식','02-466-3550','Y',1130,2100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('전자방','중식','서울시 성동구 성수동2가 299-157','N','3',' 최신 중식 니즈를 반영한 중국집.','정통중식,일반중식','02-420-1193','Y',1130,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('샤오짠','중식','서울시 성동구 성수동2가 322-4','N','3','가성비 좋은 대만 음식을 원한다면 "샤오짠"','대만음식','02-499-4427','N',1130,2100,'연중무휴');											

--여의도(이창택)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('정인면옥','한식','서울시 영등포구 여의도동 13-1','N','4.4','담백하고 맛있는 평양냉면','국수,면요리','02-2683-2615','Y',1130,2130,'토');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('신원','한식','서울시 영등포구 여의도동 23-5','N','4.2','밥도둑 칼칼한 우거지고등어조림','한정식,백반,정통한식','02-3772-8366','Y',1100,2230,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('진주집','한식','서울시 영등포구 여의도동 36-2','N','4.1','이영자 맛집리스트에도 올라와있는 콩국수, 닭칼국수','국수,면요리','02-780-6108','Y',1000,2000,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('송추가마골인어반','한식','서울시 영등포구 여의도동 25-11','N','4.1','다양한 양념갈비와 한우, 푸짐한 갈비탕','고기요리, 갈비','02-783-6608','Y',1100,2200,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('대원','한식','서울시 영등포구 여의도동 36-4','N','3.8','언제나 깔끔한 생선구이','생선구이','02-784-0879','N',1100,2400,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('에덴식당','한식','서울시 영등포구 여의도동 36','N','4.1','지리산 산나물과 부드러운 된장찌개','한정식,백반,정통한식','02-786-3119','Y',1100,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('서궁','중식','서울시 영등포구 여의도동 43-4','N','3.8','군만두가 짱 맛있는 식신로드 탕수육','정통중식,일반중식','02-780-7548','Y',1100,2130,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('피슈마라홍탕','중식','서울시 영등포구 여의도동 35-2','N','3.7','직장인 마라 맛집','마라샹궈, 기타중식','02-780-3330','Y',1100,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('모던눌랑','중식','서울시 영등포구 여의도동 45-1','N','3.6','1930년 대 상하이 문화의 현대적인 신여성을 컨셉으로 만들어진 부띠크 차이니즈 다이닝','정통중식,일반중식','02-6484-5980','Y',1100,2300,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('밍 1956','중식','서울시 영등포구 여의도동 44-21','N','3.5','깔끔해서 여자들이 좋아하는 퓨전 중식집','정통중식,일반중식','02-761-4242','Y',1000,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('하노','중식','서울시 영등포구 여의도동 40','N','3','푸짐하고 맛도 좋은데 가격도 착한 중국집','정통중식,일반중식','02-782-7373','N',1100,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('호우양꼬치','중식','서울시 영등포구 여의도동 21-3','N','3','양꼬치하면 호우 양꼬치!','양꼬치 ','02-6335-9292','Y',1400,2400,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('피그인더가든','양식','서울시 영등포구 여의도동23-5','N','4.3','건강하고 고급진 맛집!','샐러드,다이어트','02-761-4272','Y',800,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('바스버거','양식','서울시 영등포구 여의도동24-1','N','4.1','이름부터 육덕진 탐욕버거','브런치, 버거','02-784-6643','Y',1100,2300,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('그리너리샐러드','양식','서울시 영등포구 여의도동13-25','N','4.1','배부른 다이어트 샐러드','다이어트,샐러드','02-782-9242','N',900,2100,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('테이스팅룸','양식','서울시 영등포구 여의도동23','N','4','재미있고 도특한 이태리요리에 한식을 접목시킨 지중해풍 요리','이탈리아음식','02-6137-5654','Y',1000,2200,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('쿠치나후','양식','서울시 영등포구 여의도동13-25','N','3.8','의정관 한강 야경 보이는 레스토랑','이탈리아음식','02-3775-3634','Y',1130,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('세상의모든아침','양식','서울시 영등포구 여의도동28-1','N','3.7','전경련회관 50층에서 여의도 전망 바라보며 브런치','브런치,버거,샌드위치','02-2055-4440','Y',900,2300,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('하쯔호','일식','서울시 영등포구 여의도동61','N','4.3','스시 오마카세 맛있는 집','회, 스시,','02-780-1634','Y',1130,2130,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('진가와','일식','서울시 영등포구 여의도동25','N','4.2','가성비 굿인 일식코스요리','라멘,소바,면요리','02-782-9072','Y',1100,2330,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('갓포아키(여의도)','일식','서울시 영등포구 여의도동 17-5','N','4.2','강남에 일식캇포요리를 유행시킨집','이자카야, 회','02-786-8661','Y',1800,100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('카레오','일식','서울시 영등포구 여의도동47','N','4','카레 자체의 맛을 제대로 내는 곳','돈부리,일본카레,벤토','02-782-4804','Y',1130,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('하루158','일식','서울시 영등포구 여의도동25','N','3.4','여의도 맛집, 초밥이 맛있는 이자카야','일반일식,초밥','02-761-7889','N',1100,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('더누들바','일식','서울시 영등포구 여의도동23','N','3.2','호텔분위기내며 가성비,맛 갑!','라멘, 면요리, 누들','02-6137-7000','Y',1100,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('커피기업','디저트','서울시 영등포구 여의도동13-25','N','4.2','여의도 비엔나 하나로 소문난 커피맛집','커피, 디저트','02-786-5671','Y',700,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('팥이재','디저트','서울시 영등포구 여의도동45-19','N','4.2','여의도 우유빙수 맛있는 곳','팥빙수, 우유빙수','02-782-1822','Y',1100,2330,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('카페진정성','디저트','서울시 영등포구 여의도동45-19','N','4','밀크티로 유명한 감성돋는 카페','커피, 녹차, 밀크티','02-6484-5133','Y',800,2100,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('패트릭스와플','디저트','서울시 영등포구 여의도동53-11','N','4','여의도에서 가장 유명한 와플집','와플,커피','02-3775-0608','Y',1130,1930,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('아이엠베이글','디저트','서울시 영등포구 여의도동43-4','N','3.9','뉴욕 3대 베이글 전문점','샌드위치,커피,베이글','070-4233-2881','Y',830,2000,'x');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('그라놀로지','디저트','서울시 영등포구 여의도동23','N','3.4','몸에도 좋고 맛도 좋은 디저트','커피, 그래놀라','02-6137-5837','Y',800,2200,'x');											


--강남(이도현)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('농민백암왕순대','한식','서울시 강남구 역삼동 830-9','N','4.6','점심에 생각나는 농민백암왕순대','탕,찌개,전골','02-501-2772','N',1110,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('진미평양냉면','한식','서울시 강남구 논현동 115-10','N','4.6','쫄깃쫄깃 탱탱한 면발','면,냉면','02-515-3469','N',1100,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('뽕나무쟁이','한식','서울시 강남구 대치동 896-5','N','4.4','야들야들한 족발','족발','02-558-9279','Y',1200,2400,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('대우부대찌개','한식','서울시 강남구 역삼동 641-18','N','4.4','보글보글 부대찌개','탕,찌개,전골','02-552-1663','Y',930,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('알고기','한식','서울시 강남구 청담동 80-17','N','4.3','쫄깃쫄깃 고기집','고기','02-3446-6925','Y',1700,2330,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('닭한마리감자탕','한식','서울시 강남구 신사동 512-18','N','4.3','얼큰한 감자탕','닭,오리','02-515-5220','Y',0,2400,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('가담','중식','서울시 강남구 신사동 608-8','N','4.7','여기가 중국인지 한국 인지 중국집','정통 중식,일반 중식','02-545-5163','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('삼창교자','중식','서울시 강남구 신사동 517-34','N','4.4','깔금한 만두 자신있는 만두','딤섬,만두','02-542-5588','Y',1130,2230,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('양식당더램키친','중식','서울시 강남구 신사동 529-6','N','4.3','요리가 맛있는 중국집','기타 중식','02-3445-9283','Y',1800,2400,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('논현양꼬치','중식','서울시 강남구 논현동 138-22','N','4.3','이영자가 추천한 맛집','기타 중식','02-516-9792','N',1800,500,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('도원','중식','서울시 강남구 삼성동 159-7','N','3.8','탕수육이 맛있는 중국집','정통 중식,일반 중식','02-3467-8390','Y',1100,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('불이아','중식','서울시 강남구 역삼동 668-14','N','4.1','매콤달콤 훠거집','기타 중식','02-556-6689','Y',1130,2400,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('톡톡','양식','서울시 강남구 청담동 69-5','N','4.8','이색맛집','이탈리안','02-542-3030','Y',1200,2200,'월');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('알라프리마','양식','서울시 강남구 논현동 42-6','N','4.8','분위기 최고.맛도 최고.친절도 최고.','이탈리안','02-511-2555','Y',1200,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('SOOT','양식','서울시 강남구 신사동 561-35','N','4.8','오직 장작과 숯으로만 요리하는 집','퓨전양식','02-6401-0306','Y',1200,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('모터시티','양식','서울시 강남구 역삼동 736-1','N','4.6','피자가 먹고싶을땐 모터시티','기타양식','02-2051-8877','Y',1100,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('다운타우너','양식','서울시 강남구 신사동 666-25','N','4.5','역시 브런치엔 다운타우너','브런치,버거,샌드위치','070-8833-3696','Y',1130,2130,'원');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('파스토','양식','서울시 강남구 청담동 19-4','N','4.5','피자 파스타 맛집','이탈리안','02-515-6878','Y',1200,2300,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('빈브라더스','디저트','서울시 강남구 역삼동 819-1','N','4.4','책읽기 좋은곳','카페,디저트','02-568-8192','N',1030,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('장꼬방','디저트','서울시 서초구 서초동 1316','N','4.1','건강한 맛!아낌없이 들어간 팥!','카페,디저트','02-597-5511','Y',900,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('아우어커피','디저트','서울시 강남구 역삼동 810-14','N','3.9','2인이 가기 좋은곳','카페,디저트','02-501-2745','N',1200,2100,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('지올리띠','디저트','서울시 강남구 역삼동 601-1','N','3.8','시간때우기 좋은곳','카페,디저트','02-563-3364','N',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('만랩커피','디저트','서울시 강남구 역삼동 818-11','N','3.7','저럼한 가격에 좋은 원두를 사용하는 만랩','카페,디저트','02-566-4718','N',1000,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('마망갸또','디저트','서울시 강남구 역삼동 812-8','N','3.9','카라멜맛집','카페,디저트','02-556-3937','N',930,2300,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('갓포아키(강남)','일식','서울시 강남구 신사동 651-5','N','4.8','다시 생각나는 맛','이자카야,오뎅,꼬치','02-540-8669','Y',1800,100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('로바타탄요','일식','서울시 강남구 신사동 584-1','N','4.7','맛없을수가 없는 음식','정통 일식,일반 일식','02-6339-9667','Y',1800,100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('정돈','일식','서울시 강남구 역삼동 811-4','N','4.6','음식도 깔끔한 집','까스요리','02-563-0924','N',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시코우지','일식','서울시 강남구 청담동 1-1','N','4.5','무엇을 생각하든 기대이상','회,스시','02-541-6200','Y',1200,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('136길육미','일식','서울시 강남구 논현동 107-34','N','4.4','메밀김밥!이것을 과연 김밥인가 김면인가?','퓨전 일식','02-542-8899','Y',1130,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('마리모','일식','서울시 강남구 신사동 653-14','N','4.2','동네에 있는 들르기 편한 선술집.','이자카야,오뎅,꼬치','02-545-5885','Y',1800,330,'연중무휴');											

--가디(이정훈)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('빌리엔젤','디저트','      서울 금천구 디지털로9길 23','N','4.6','데이트하기좋은','카페 디저트','02-2067-3628','N',1030,2100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('에프터투마카롱','디저트','서울 금천구 디지털로 206','N','4.6','대한민국No.1마카롱','카페 디저트','010-7740-5016','N',1200,2000,'월,화');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('치즈팩토리','디저트','서울 금천구 벚꽃로 298','N','4.4','직장인이 퇴근후 업무하기 좋은','카페 디저트','02-830-1887','Y',700,1900,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('카페스미다','디저트','서울 금천구 벚꽃로 298','N','4.4','원두를 직접내린','카페 디저트','070-4633-2525','Y',1130,2330,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('타미하우스','디저트','서울 금천구 벚꽃로 286','N','4.3','샌드위치,빙수가맛있는','카페 디저트','02-855-5828','Y',0.458333333333333,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('플레잉디오븐','디저트','서울 금천구 벚꽃로 278','N','4.3','마카롱장인이순수만든','카페 디저트','010-2911-3630','Y',1200,2000,'월,화,토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('달달보드레','양식','서울 금천구 디지털로10길 9','N','4.7','여러가지 양식종류가먹고싶을땐','스테이크,파스타,오믈렛','02-2136-2233','Y',1100,2130,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('더제이케이키친박스','양식','서울 금천구 가산디지털1로 145','N','4.4','오븟하게 둘이먹기좋은','이탈리아음식,파스타','02-2624-0008','Y',1130,2100,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('롱블랙스푼','양식','서울 금천구 가산디지털1로 131','N','4.3','금천구인이 맜잇다고 소문낸','스테이크,파스타','02-6947-7788','Y',1100,2200,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('마피아피자','양식','서울 금천구 가산디지털1로 168','N','4.3','둘이먹다한명이쓰러져도모를','피자,펍','02-2026-0026','N',1130,2330,'토일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('매드포갈릭','양식','서울 금천구 디지털로10길 9','N','3.8','이탈리아음식이먹고싶을떈','이탈리아음식','02-2136-9982','Y',1100,2130,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('호세가','양식','서울 금천구 디지털로10길 9','N','4.1','멕시코본연에맛을느끼고싶다면','멕시코,남미음식','02-556-6689','Y',1130,2400,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('가츠나베','일식','서울 금천구 가산디지털1로 186','N','4.8','가성비와퀄리티가좋은','돈가스,우동,라멘,우동','02-2028-5335','Y',1200,2200,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('단또','일식','서울 금천구 디지털로9길 32','N','4.8','일본인이칭찬한 라맨맛집','논현동 이탈리안','02-857-1852','Y',1200,2100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('멘무샤(가산)','일식','서울 금천구 가산디지털1로 168','N','4.8','추운날먹기좋은라맨','일본식라면','02-2026-0090','Y',1100,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시천','일식','서울 금천구 벚꽃로 298','N','4.6','최상에 물고기에 퀄리티','초밥,롤','02-868-5188','Y',1100,2130,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시히또','일식','서울 금천구 벚꽃로 286','N','4.5','입안에서 물고기가 살아숨쉬는','초밥,롤','02-6953-0105','Y',1130,2130,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('하코야라멘','일식','서울 금천구 가산디지털1로 205','N','4.5','수타에장인이 만든','라멘,소바,우동','02-6111-8577','Y',1200,2300,'토일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('만다린','중식','서울 금천구 가산디지털1로 186','N','4.4','먹는순간중국이라는환상을갖게되는','중식당','02-2028-5556','N',1030,2130,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('미가양꼬치','중식','서울 금천구 벚꽃로42길 5','N','4.1','양꼬치입문자도좋아하는','양꼬치','02-837-3003','Y',900,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('삼팔교자관','중식','서울 금천구 가산디지털1로 168','N','3.9','최고에셰프가운영하는','중식당','02-856-3868','N',1200,2100,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('예원','중식','서울 금천구 가산디지털1로 145','N','3.8','탕수육이 맛있는','중식당','02-2624-0777','N',1100,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('이사장요리니하우','중식','서울 금천구 벚꽃로40길 29','N','3.7','음식맛을 잊을수 없는','중식당','02-863-4003','N',1000,2200,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('황제짬뽕양꼬치','중식','서울 금천구 디지털로9길 32','N','3.9','비린맛떄문에 못먹는 사람을 위한','중식당','02-2106-8530','N',1100,2300,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('동남집','한식','서울 금천구 가산디지털1로 149','N','4.8','추운날 생각나기 좋은 갈비탕','갈비탕','02-830-8834','Y',1800,100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('돼지분식','한식','서울 금천구 가산로9길 16','N','4.7','분식이 생각날땐 돼지분식','한식','02-853-6550','Y',1800,100,'토,일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('서천쭈꾸미대구탕','한식','서울 금천구 벚꽃로38길 42','N','4.6','매콤한게 생각날떄 오게되는','한식','070-8865-0400','N',1130,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('순남시래기','한식','서울 금천구 가산디지털1로 186','N','4.5','옛추억이 생각난다면','백반,가정식','02-866-4555','Y',1100,2200,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('순대의명가미각','한식','서울 금천구 벚꽃로 286','N','4.4','최고의가성비로 포만감을 주는','순대,순대국','02-866-9600','Y',1130,2100,'');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('용호동낙지','한식','서울 금천구 가산디지털1로 186','N','4.2','살아숨쉬는 낙지맛이 생각난다면','낙지요리','02-2028-4578','Y',1800,330,'일');

--판교(정진섭)
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('비와별닭갈비','한식','경기 성남시 분당구 동판교로177번길 25','N','5','담백한 맛이 일품인 닭갈비집','닭갈비','031-8016-7999','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('크래버대게나라','한식','경기 성남시 분당구 판교역로 178','N','4','대게 대게가 먹고 싶은날 ','대게','031-8016-5593','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('찬장','한식','경기 성남시 분당구 대왕판교로606번길 10','N','4','가까운 사람들 바른식사','생선구이, 찌개','031-781-7337','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('사위식당','한식','경기 성남시 분당구 판교역로 152','N','3','사위들이 장모님의 마음으로 준비한 식당','낙지, 곱창, 새우','031-622-7180','Y',1130,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('진진반상','한식','경기 성남시 분당구 대왕판교로 660','N','4','우리의 땅에서 생산된 좋은 식재로 만든 올바른 음식','한정식','031-724-2733','Y',1130,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('얼룩도야지','한식','경기 성남시 분당구 대왕판교로606번길 45','N','4','프리미엄 슈퍼 포크 돼지고기집','돼지고기','031-8017-2840','Y',1100,2300,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('센트럴차이나','중식','경기 성남시 분당구 판교역로192번길 14-1','N','4','판교 회식장소로 좋은 중식당','짜장면, 탕수육, 양장피','031-8017-8615','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('제이스팟','중식','경기 성남시 분당구 판교역로 152','N','5','고기 빛깔부터 다른 정말 맛있는 훠궈','훠궈','031-622-7179','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('차알','중식','경기 성남시 분당구 동판교로 177','N','4','아메리칸 스타일 중식집','중식코스, 짜장면, 탕수육','031-701-7679','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('최고집손짬뽕','중식','경기 성남시 분당구 판교역로10번길 12-9','N','3','건더기가 많은 손짬뽕집','짜장면, 짬뽕, 손짜장, 손짬뽕','031-8017-6350','Y',1030,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('왕스덕','중식','경기 성남시 분당구 대왕판교로645번길 36','N','4','청나라 황실 오리구이의 전통을 계승한 전취덕 방식의 북경오리 전문점','북경오리, 꿔바로우, 칠리새우','031-606-8517','Y',1100,2100,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('마라공방','중식','경기 성남시 분당구 판교역로192번길 12','N','5','깔끔하게 맛있는 마라탕','마라탕, 마라샹궈, 꿔바로우','031-8061-0780','Y',1030,2230,'일');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('히카루후','일식','경기 성남시 분당구 동판교로177번길 25','N','5','신선한 재료로 최고의 맛과 정성을 다하는 덮밥집','덮밥','031-626-0073','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('후라토식당','일식','경기 성남시 분당구 동판교로177번길 25','N','4','훌쩍 떠난 일본 도쿄 여행에서 시작된 덮밥집','덮밥','031-607-7090','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('긴자','일식','경기 성남시 분당구 판교로 185','N','3','룸시설 완비 정갈한 일식집','초밥, 회, 스시, 사시미','031-702-9461','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('매일식당','일식','경기 성남시 분당구 판교역로192번길 14-2','N','4','수제 돈까스, 함박 스테이크 전문점','돈까스, 함박스테이크','031-8016-2623','Y',1100,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('스시혼','일식','경기 성남시 분당구 동판교로177번길 25','N','5','분위기 좋고 맛도 깔끔한 스시집','초밥, 회, 스시, 사시미','031-701-0923','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('하코야','일식','경기 성남시 분당구 분당내곡로 151','N','4','돈까스,라이스 그리고 누들요리 전문점','라멘, 돈까스, 덮밥','031-705-0337','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('감성타코','양식','경기 성남시 분당구 동판교로177번길 25','N','5','멕시칸 케쥬얼 레스토랑 감성타코','타코, 또띠야, 멕시칸','031-781-8885','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('울프스덴','양식','경기 성남시 분당구 대왕판교로 660','N','4','판교 파스타, 스테이크 맛집','파스타, 스테이크, 피자','031-628-1887','Y',1100,2300,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('어글리스토브','양식','경기 성남시 분당구 판교역로 145','N','4','자연그대로의 환경에서 자란 음식','스테이크, 샐러드, 토스트, 파스타','031-706-8459','Y',1000,2130,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('내니스','양식','경기 성남시 분당구 동판교로177번길 25','N','5',' 전문여행가와 햄버거 장인이 만나 최고의 수제버거','햄버거','070-4113-0099','Y',1130,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('뚜에이오','양식','경기 성남시 분당구 운중로225번길 14-1','N','4','형제 오너쉐프가 오픈된 주방에서 선보이는 가정식 파스타와 스테이크','파스타, 브런치','031-8016-1865','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('비비','양식','경기 성남시 분당구 산운로160번길 12','N','3','판교 운중동에 위치한 스페인요리','감바스, 파스타 스테이크','031-609-6789','Y',1100,2200,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('달달이','디저트','경기 성남시 분당구 운중로 242','N','4','판교 창밖 풍경이 멋진 카페','커피, 카페, 케이크','031-705-8882','Y',1100,1900,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('메이크어케이크','디저트','경기 성남시 분당구 동판교로177번길 25','N','5','커피가 맛있는 카페','커피, 카페, 케이크','031-708-7040','Y',1100,2100,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('Yam2','디저트','경기 성남시 분당구 판교역로10번길 14-3','N','4','케이크전문 베이커리','케이크, 홍차, 커피','031-8017-1992','Y',1100,1900,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('위베이커리','디저트','경기 성남시 분당구 운중로166번길 4-2','N','4','케이크전문 베이커리','케이크, 스콘, 식빵','031-607-2461','Y',1000,2000,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('세시셀라','디저트','경기 성남시 분당구 분당내곡로 151','N','5','당근케잌이 유명한 맛있는 카페','케이크, 당근케이크, 에이드, 스무디','031-8016-7101','Y',1100,2300,'연중무휴');											
insert into left34.restaurant (r_name, type, location, best_yn, grade, description, category, r_phone, parking_yn, open_time, close_time, holiday) values ('까치화방','디저트','경기 성남시 분당구 판교역로 152','N','4','건강한 제조 공법으로 만든 수제청','수제청, 베이커리','031-622-7291','Y',1000,2200,'연중무휴');