/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-30 06:20:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577412347786L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577642325067L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("<link rel=\"styleSheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/frame.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div id=\"innerHead\">\n");
      out.write("            <div class=\"headerWrapper\">\n");
      out.write("                <form>\n");
      out.write("                    <div class=\"search__SearchBlock\">\n");
      out.write("                        <input type=\"text\" placeholder=\"지역, 식당 또는 음식을 입력하세요\">\n");
      out.write("                        <button class=\"search__SearchButton\">\n");
      out.write("                            <span></span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"realtimeKeyWord_rolling_base\">\n");
      out.write("                        <h3 class=\"blind\">급상승 검색어</h3>\n");
      out.write("                        <div class=\"realtimeKeyWord_rolling\">\n");
      out.write("                            <ul class=\"ah_1\">\n");
      out.write("                                <li class=\"ah_item\">\n");
      out.write("                                    <a href=\"\" class=\"ah_a\">\n");
      out.write("                                        <span class=\"ah_r\">1</span>\n");
      out.write("                                        <span class=\"ah_k\">강남역</span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"ah_ico_open\">\n");
      out.write("​\n");
      out.write("                    </span>\n");
      out.write("​\n");
      out.write("                </form>\n");
      out.write("                <h1 class=\"title__TitleWrapper\">\n");
      out.write("                    <a href=\"\" class=\"title__Link\">\n");
      out.write("                        <i class=\"Header__LogoIcon\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </h1>\n");
      out.write("                <a href=\"/mypage/index\" class=\"mypage__Link\">\n");
      out.write("                    <span class=\"mypage__Icon\"></span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <hr class=\"hide\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<h4>header/footer 테스트</h4>\n");
      out.write("\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/searchList\">검색후 화면</a>\t\n");
      out.write("<a href=\"");
      out.print(request.getContextPath() );
      out.write("/restaurants\">상세화면</a>\t\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <footer>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <div class=\"inner__Copy\">\n");
      out.write("                <h2 class=\"screen_out\">서비스 이용정보</h2>\n");
      out.write("                <div class=\"info_service\">\n");
      out.write("                    <a href=\"#\" class=\"link_service link_company\">회사소개</a>\n");
      out.write("                    <a href=\"#\" class=\"link_service link_service2\">개인정보처리방침</a>\n");
      out.write("                    <a href=\"#\" class=\"link_service link_service2\">광고/제휴문의</a>\n");
      out.write("                </div>\n");
      out.write("​\n");
      out.write("                <div class=\"copyrights\">\n");
      out.write("                    <small>\n");
      out.write("                        <span class=\"txt_copy\">㈜left34</span>\n");
      out.write("                        <span class=\"txt_copy\">서울특별시 강남구 역삼동</span>\n");
      out.write("                        <span class=\"txt_copy\">대표이사: JEON HEE JIN(전희진)</span>\n");
      out.write("                        <span class=\"txt_copy\">사업자 등록번호: 219-12-18109</span>\n");
      out.write("                        <span class=\"txt_copy\">통신판매업 신고번호: 219-12-18109</span>\n");
      out.write("                        <span class=\"txt_copy\">고객센터: 02-1234-5678</span>\n");
      out.write("                        <span class=\"copyright\">© 2019 Eat's Twelve Co., Ltd. All rights reserved.</span>\n");
      out.write("                    </small>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>    \n");
      out.write("</body>\n");
      out.write("</html>   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
