/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.47
 * Generated at: 2019-12-30 06:50:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.board;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1577412347786L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1577642325067L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script src=\"");
      out.print(request.getContextPath() );
      out.write("/js/jquery-3.4.1.js\"></script>\n");
      out.write("<link rel=\"styleSheet\" href=\"");
      out.print(request.getContextPath() );
      out.write("/css/frame.css\" />\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <header>\n");
      out.write("        <div id=\"innerHead\">\n");
      out.write("            <div class=\"headerWrapper\">\n");
      out.write("                <form>\n");
      out.write("                    <div class=\"search__SearchBlock\">\n");
      out.write("                        <input type=\"text\" placeholder=\"지역, 식당 또는 음식을 입력하세요\">\n");
      out.write("                        <button class=\"search__SearchButton\">\n");
      out.write("                            <span></span>\n");
      out.write("                        </button>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"realtimeKeyWord_rolling_base\">\n");
      out.write("                        <h3 class=\"blind\">급상승 검색어</h3>\n");
      out.write("                        <div class=\"realtimeKeyWord_rolling\">\n");
      out.write("                            <ul class=\"ah_1\">\n");
      out.write("                                <li class=\"ah_item\">\n");
      out.write("                                    <a href=\"\" class=\"ah_a\">\n");
      out.write("                                        <span class=\"ah_r\">1</span>\n");
      out.write("                                        <span class=\"ah_k\">강남역</span>\n");
      out.write("                                    </a>\n");
      out.write("                                </li>\n");
      out.write("                            </ul>\n");
      out.write("                        </div>\n");
      out.write("                    </div>\n");
      out.write("                    <span class=\"ah_ico_open\">\n");
      out.write("​\n");
      out.write("                    </span>\n");
      out.write("​\n");
      out.write("                </form>\n");
      out.write("                <h1 class=\"title__TitleWrapper\">\n");
      out.write("                    <a href=\"\" class=\"title__Link\">\n");
      out.write("                        <i class=\"Header__LogoIcon\"></i>\n");
      out.write("                    </a>\n");
      out.write("                </h1>\n");
      out.write("                <a href=\"/mypage/index\" class=\"mypage__Link\">\n");
      out.write("                    <span class=\"mypage__Icon\"></span>\n");
      out.write("                </a>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </header>\n");
      out.write("    <hr class=\"hide\">\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/frame.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(request.getContextPath());
      out.write("/css/boardView.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=4d9befe9bbff1160082ea828e900ce9c\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"//dapi.kakao.com/v2/maps/sdk.js?appkey=APIKEY&libraries=services,clusterer\"></script>\r\n");
      out.write("<body class=\"ng-scope\">\r\n");
      out.write("    <main class=\"pg-restaurant ng-scope\">\r\n");
      out.write("        <article class=\"contents\">\r\n");
      out.write("            <!-- 레스토랑 상세 이미지 슬라이드 -->\r\n");
      out.write("            <aside class=\"restaurant-photos\">\r\n");
      out.write("                <div class=\"list-photo_wrap owl-carousel owl-theme\" style=\"opacity: 1; display: block;\">\r\n");
      out.write("                    <div class=\"owl-wrapper-outer\">\r\n");
      out.write("                        <div class=\"owl-wrapper\" style=\"width: 3000px; left: 0px; display: block; transition: all 0ms ease 0s; transform: translate3d(0px, 0px, 0px);\">\r\n");
      out.write("                            <div class=\"owl-item\" style=\"width: 300px;\">\r\n");
      out.write("                                <figure class=\"list-photo\">\r\n");
      out.write("                                    <figure class=\"restaurant-photos-item\">\r\n");
      out.write("                                        <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/268918/512536_1490184275055_16308?fit=around|512:512&crop=512:512;*,*&output-format=jpg&output-quality=80\" alt=\"\" class=\"center-croping\" onerror=\"\">\r\n");
      out.write("                                        <div class=\"last_image\">\r\n");
      out.write("                                            <p class=\"txt\">\r\n");
      out.write("                                                                        \r\n");
      out.write("                                            사진 더보기\r\n");
      out.write("                    \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"arrow-white\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"owl-item\" style=\"width: 300px;\">\r\n");
      out.write("                                <figure class=\"list-photo\">\r\n");
      out.write("                                    <figure class=\"restaurant-photos-item\" role=\"img\">\r\n");
      out.write("                                        <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/479674_1577394694974854.jpg?fit=around|512:512&crop=512:512;*,*&output-format=jpg&output-quality=80\" alt=\"\" class=\"center-croping\">\r\n");
      out.write("                                        <div class=\"last_image\">\r\n");
      out.write("                                            <p class=\"txt\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            사진 더보기\r\n");
      out.write("                    \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"arrow-white\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"owl-item\" style=\"width: 300px;\">\r\n");
      out.write("                                <figure class=\"list-photo\">\r\n");
      out.write("                                    <figure class=\"restaurant-photos-item\" role=\"img\">\r\n");
      out.write("                                        <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/479674_1577394697152263.jpg?fit=around|512:512&crop=512:512;*,*&output-format=jpg&output-quality=80\" alt=\"\" class=\"center-croping\">\r\n");
      out.write("                                        <div class=\"last_image\">\r\n");
      out.write("                                            <p class=\"txt\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            사진 더보기\r\n");
      out.write("                    \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"arrow-white\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"owl-item\" style=\"width: 300px;\">\r\n");
      out.write("                                <figure class=\"list-photo\">\r\n");
      out.write("                                    <figure class=\"restaurant-photos-item\" role=\"img\">\r\n");
      out.write("                                        <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/479674_1577394698145112.jpg?fit=around|512:512&crop=512:512;*,*&output-format=jpg&output-quality=80\" alt=\"\" class=\"center-croping\">\r\n");
      out.write("                                        <div class=\"last_image\">\r\n");
      out.write("                                            <p class=\"txt\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            사진 더보기\r\n");
      out.write("                    \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"arrow-white\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"owl-item\" style=\"width: 300px;\">\r\n");
      out.write("                                <figure class=\"list-photo\">\r\n");
      out.write("                                    <figure class=\"restaurant-photos-item\" role=\"img\">\r\n");
      out.write("                                        <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/479674_1577394698795774.jpg?fit=around|512:512&crop=512:512;*,*&output-format=jpg&output-quality=80\" alt=\"\" class=\"center-croping\">\r\n");
      out.write("                                        <div class=\"last_image\">\r\n");
      out.write("                                            <p class=\"txt\">\r\n");
      out.write("                                                \r\n");
      out.write("                                            사진 더보기\r\n");
      out.write("                    \r\n");
      out.write("                                            </p>\r\n");
      out.write("                                            <span class=\"arrow-white\"></span>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </figure>\r\n");
      out.write("                                </figure>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"owl-controls clickable\" style=\"display: block;\">\r\n");
      out.write("                        <div class=\"owl-buttons\">\r\n");
      out.write("                            <div class=\"owl-prev\">\r\n");
      out.write("                                <button class=\"btn-nav prev\" style=\"display: none;\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"owl-next\">\r\n");
      out.write("                                <button class=\"btn-nav next\"></button>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </aside>\r\n");
      out.write("            \r\n");
      out.write("            <!-- 레스토랑 상세 정보 -->\r\n");
      out.write("            <div class=\"column-wrapper\">\r\n");
      out.write("                \r\n");
      out.write("                <!-- 컨텐츠 영역 -->\r\n");
      out.write("                <div class=\"column-contents\">\r\n");
      out.write("                    <div class=\"inner\">\r\n");
      out.write("                        <!-- 레스토랑 상세 -->\r\n");
      out.write("                        <section class=\"restaurant-detail\">\r\n");
      out.write("                            <header>\r\n");
      out.write("                                <div class=\"restaurant_title_wrap\">\r\n");
      out.write("                                    <span class=\"title\">\r\n");
      out.write("                                            <h1 class=\"restaurant_name\">백정돈공장</h1>\r\n");
      out.write("                                        <strong class=\"rate-point\">\r\n");
      out.write("                                            <span>4.6</span>\r\n");
      out.write("                                        </strong>\r\n");
      out.write("                                        <p class=\"branch\"></p>\r\n");
      out.write("                                    </span>\r\n");
      out.write("                                    <div class=\"restaurant_action_button_wrap\">\r\n");
      out.write("                                        <button class=\"review_writing_button\">\r\n");
      out.write("                                            <i class=\"review_writing_button_icon\"></i>\r\n");
      out.write("                                            <span class=\"review_writing_button_text\">리뷰쓰기</span>\r\n");
      out.write("                                        </button>\r\n");
      out.write("                                        <div class=\"wannago_wrap\">\r\n");
      out.write("                                            <button class=\"btn-type-icon favorite wannago_btn \" data-restaurant_uuid=\"268918\" data-action_id=\"\"></button>\r\n");
      out.write("                                            <p class=\"wannago_txt\">가고싶다</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                \r\n");
      out.write("                                <div class=\"status\r\n");
      out.write("                                branch_none\r\n");
      out.write("                                \">\r\n");
      out.write("                                <span class=\"cnt hit\">11,871</span>\r\n");
      out.write("                                <span class=\"cnt review\">10</span>\r\n");
      out.write("                                <span class=\"cnt favorite\">413</span>\r\n");
      out.write("                              </div>\r\n");
      out.write("                            </header>\r\n");
      out.write("\r\n");
      out.write("                                <!-- 상세 정보 -->\r\n");
      out.write("                                <table class=\"info no_menu\">\r\n");
      out.write("                                <caption>레스토랑 상세 정보</caption>\r\n");
      out.write("\r\n");
      out.write("                                <tbody>\r\n");
      out.write("                                <tr class=\"only-desktop\">\r\n");
      out.write("                                    <th>주소</th>\r\n");
      out.write("                                    <td>서울시 성동구 성수동2가 310-1</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr class=\"only-desktop\">\r\n");
      out.write("                                    <th>전화번호</th>\r\n");
      out.write("                                    <td>02-462-8295</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>음식 종류</th>\r\n");
      out.write("                                    <td>\r\n");
      out.write("                                    <span>고기 요리</span>\r\n");
      out.write("                                    </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>가격대</th>\r\n");
      out.write("                                    <td>만원-2만원</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>주차</th>\r\n");
      out.write("                                    <td>주차공간없음 </td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th style=\"vertical-align:top;\">영업시간</th>\r\n");
      out.write("                                    <td>17:00 - 24:00</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                <tr>\r\n");
      out.write("                                    <th>휴일</th>\r\n");
      out.write("                                    <td>일</td>\r\n");
      out.write("                                </tr>\r\n");
      out.write("\r\n");
      out.write("                                </tbody>\r\n");
      out.write("                            </table>\r\n");
      out.write("\r\n");
      out.write("                                <p class=\"update_date\">\r\n");
      out.write("                                업데이트\r\n");
      out.write("                                : 2019. 5. 31\r\n");
      out.write("                                </p>\r\n");
      out.write("\r\n");
      out.write("                            <div id=\"reviewListFocusId\"></div>\r\n");
      out.write("\r\n");
      out.write("                        </section>\r\n");
      out.write("                        <section class=\"restaurant_introduce_section\">\r\n");
      out.write("                            <div class=\"RestaurantIntroduceSection\"></div>\r\n");
      out.write("                        </section>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                \r\n");
      out.write("                <!-- 사이드 영역 -->\r\n");
      out.write("                <div class=\"side-wrap\">\r\n");
      out.write("                    <div class=\"column-side\">\r\n");
      out.write("                        <!--지도-->\r\n");
      out.write("                        <div class=\"map-container\" style=\"position: relative; overflow: hidden; background: url('https://https://ssl.pstatic.net/static/maps/mantle/1x/pattern_1.png') 0px 0px repeat transparnet;\">\r\n");
      out.write("                            <div class=\"map_layer\" id=\"map\">\r\n");
      out.write("                                <script>\r\n");
      out.write("                                // 이미지 지도에서 마커가 표시될 위치입니다 \r\n");
      out.write("                                var markerPosition  = new kakao.maps.LatLng(37.545405, 127.050109); \r\n");
      out.write("\r\n");
      out.write("                                // 이미지 지도에 표시할 마커입니다\r\n");
      out.write("                                // 이미지 지도에 표시할 마커는 Object 형태입니다\r\n");
      out.write("                                var marker = {\r\n");
      out.write("                                    position: markerPosition\r\n");
      out.write("                                };\r\n");
      out.write("\r\n");
      out.write("                                var staticMapContainer  = document.getElementById('map'), // 이미지 지도를 표시할 div  \r\n");
      out.write("                                    staticMapOption = { \r\n");
      out.write("                                        center: new kakao.maps.LatLng(37.545405, 127.050109), // 이미지 지도의 중심좌표\r\n");
      out.write("                                        level: 3, // 이미지 지도의 확대 레벨\r\n");
      out.write("                                        marker: marker // 이미지 지도에 표시할 마커 \r\n");
      out.write("                                    };    \r\n");
      out.write("\r\n");
      out.write("                                // 이미지 지도를 생성합니다\r\n");
      out.write("                                var staticMap = new kakao.maps.StaticMap(staticMapContainer, staticMapOption);\r\n");
      out.write("                                </script>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"inner\">\r\n");
      out.write("                            <!-- 주변 인기 식당 -->\r\n");
      out.write("                            <section class=\"module near-rastaurant NearByRestaurantList\">\r\n");
      out.write("                                <span class=\"title NearByRestaurantList__Title\">주변 인기 식당</span>\r\n");
      out.write("                                <ul class=\"list-restaurants type-single NearByRestaurantList__List\">\r\n");
      out.write("                                    <li class=\"NearByRestaurantItem NearByRestaurantList__Item\">\r\n");
      out.write("                                        <div class=\"NearByRestaurantItem__PictureAndContent\">\r\n");
      out.write("                                            <a href=\"\" class=\"NearByRestaurantItem__PictureLink\">\r\n");
      out.write("                                                <img alt=\"\" class=\"NearByRestaurantItem__Picture loaded\" src=\"https://mp-seoul-image-production-s3.mangoplate.com/49369_1428403105589?fit=around|383:383&crop=383:383;*,*&output-format=jpg&output-quality=80\" data-was-processed=\"true\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"NearByRestaurantItem__Content\">\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__NameWrap\">\r\n");
      out.write("                                                    <a href=\"\" class=\"NearByRestaurantItem__Name\">소문난성수감자탕</a>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Rating\">4.1</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__MetroAndCuisine\">\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Metro\">왕십리/성동</span>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__SubCuisine\">탕 / 찌개 / 전골</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__InfoWrap\">\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            음식 종류\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--SubCuisine\">탕 / 찌개 / 전골</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            위치\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--Metro\">왕십리 / 성동</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            가격대\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--PriceRange\">만원 미만</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"NearByRestaurantItem NearByRestaurantList__Item\">\r\n");
      out.write("                                        <div class=\"NearByRestaurantItem__PictureAndContent\">\r\n");
      out.write("                                            <a href=\"\" class=\"NearByRestaurantItem__PictureLink\">\r\n");
      out.write("                                                <img alt=\"\" class=\"NearByRestaurantItem__Picture loaded\" src=\"https://mp-seoul-image-production-s3.mangoplate.com/49369_1428403105589?fit=around|383:383&crop=383:383;*,*&output-format=jpg&output-quality=80\" data-was-processed=\"true\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"NearByRestaurantItem__Content\">\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__NameWrap\">\r\n");
      out.write("                                                    <a href=\"\" class=\"NearByRestaurantItem__Name\">소문난성수감자탕</a>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Rating\">4.1</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__MetroAndCuisine\">\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Metro\">왕십리/성동</span>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__SubCuisine\">탕 / 찌개 / 전골</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__InfoWrap\">\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            음식 종류\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--SubCuisine\">탕 / 찌개 / 전골</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            위치\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--Metro\">왕십리 / 성동</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            가격대\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--PriceRange\">만원 미만</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"NearByRestaurantItem NearByRestaurantList__Item\">\r\n");
      out.write("                                        <div class=\"NearByRestaurantItem__PictureAndContent\">\r\n");
      out.write("                                            <a href=\"\" class=\"NearByRestaurantItem__PictureLink\">\r\n");
      out.write("                                                <img alt=\"\" class=\"NearByRestaurantItem__Picture loaded\" src=\"https://mp-seoul-image-production-s3.mangoplate.com/49369_1428403105589?fit=around|383:383&crop=383:383;*,*&output-format=jpg&output-quality=80\" data-was-processed=\"true\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"NearByRestaurantItem__Content\">\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__NameWrap\">\r\n");
      out.write("                                                    <a href=\"\" class=\"NearByRestaurantItem__Name\">소문난성수감자탕</a>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Rating\">4.1</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__MetroAndCuisine\">\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Metro\">왕십리/성동</span>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__SubCuisine\">탕 / 찌개 / 전골</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__InfoWrap\">\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            음식 종류\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--SubCuisine\">탕 / 찌개 / 전골</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            위치\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--Metro\">왕십리 / 성동</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            가격대\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--PriceRange\">만원 미만</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                    <li class=\"NearByRestaurantItem NearByRestaurantList__Item\">\r\n");
      out.write("                                        <div class=\"NearByRestaurantItem__PictureAndContent\">\r\n");
      out.write("                                            <a href=\"\" class=\"NearByRestaurantItem__PictureLink\">\r\n");
      out.write("                                                <img alt=\"\" class=\"NearByRestaurantItem__Picture loaded\" src=\"https://mp-seoul-image-production-s3.mangoplate.com/49369_1428403105589?fit=around|383:383&crop=383:383;*,*&output-format=jpg&output-quality=80\" data-was-processed=\"true\">\r\n");
      out.write("                                            </a>\r\n");
      out.write("                                            <div class=\"NearByRestaurantItem__Content\">\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__NameWrap\">\r\n");
      out.write("                                                    <a href=\"\" class=\"NearByRestaurantItem__Name\">소문난성수감자탕</a>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Rating\">4.1</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__MetroAndCuisine\">\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__Metro\">왕십리/성동</span>\r\n");
      out.write("                                                    <span class=\"NearByRestaurantItem__SubCuisine\">탕 / 찌개 / 전골</span>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                                <div class=\"NearByRestaurantItem__InfoWrap\">\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            음식 종류\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--SubCuisine\">탕 / 찌개 / 전골</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            위치\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--Metro\">왕십리 / 성동</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                    <dl class=\"NearByRestaurantItem__Info\">\r\n");
      out.write("                                                        <dt class=\"NearByRestaurantItem__InfoLabel\">\r\n");
      out.write("                                                            가격대\r\n");
      out.write("                                                        </dt>\r\n");
      out.write("                                                        <dd class=\"NearByRestaurantItem__InfoValue NearByRestaurantItem__InfoValue--PriceRange\">만원 미만</dd>\r\n");
      out.write("                                                    </dl>\r\n");
      out.write("                                                </div>\r\n");
      out.write("                                            </div>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                            </section>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("        </article>\r\n");
      out.write("    </main>\r\n");
      out.write("\r\n");
      out.write("    <!-- 이미지 클릭 시 -->\r\n");
      out.write("    <div id=\"mp20_gallery\" class=\"on\">\r\n");
      out.write("        <style>\r\n");
      out.write("            .fotorama1577680126536 .fotorama__nav--thumbs .fotorama__nav__frame{\r\n");
      out.write("            padding:2px;\r\n");
      out.write("            height:64px}\r\n");
      out.write("            .fotorama1577680126536 .fotorama__thumb-border{\r\n");
      out.write("            height:60px;\r\n");
      out.write("            border-width:2px;\r\n");
      out.write("            margin-top:2px}\r\n");
      out.write("        </style>\r\n");
      out.write("        <div class=\"fotorama--hidden\"></div>\r\n");
      out.write("        <div class=\"picture_area fotorama fotorama1577680126536\" data-auto=\"false\">\r\n");
      out.write("            <div class=\"fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--no-controls\" style=\"width: 579.4px; min-width: 0px; max-width: 100%;\">\r\n");
      out.write("                <div class=\"fotorama__stage\" style=\"width: 579px; height: 530px;\">\r\n");
      out.write("                    <div class=\"fotorama__stage__shaft fotorama__grab\" style=\"transition-duration: 0ms; transform: translate3d(0px, 0px, 0px); width: 579px; margin-left: 0px;\">\r\n");
      out.write("                        <div class=\"fotorama__stage__frame fotorama__loaded fotorama__loaded--img\" style=\"left: -581px;\">\r\n");
      out.write("                            <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/882510_1516984909816099.jpg\" alt=\"\" class=\"fotorama__img\" style=\"width: 579px; height: 433.967px; left: 0px; top: 48.0164px;\">    \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"fotorama__stage__frame fotorama__loaded fotorama__loaded--img\" style=\"left: 581px;\">\r\n");
      out.write("                            <img src=\"https://mp-seoul-image-production-s3.mangoplate.com/1340_1577594020221350.jpg\" alt=\"\" class=\"fotorama__img\" style=\"width: 397.5px; height: 530px; left: 90.75px; top: 0px;\">\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"fotorama__arr fotorama__arr--prev\" tabindex=\"0\" role=\"button\"></div>\r\n");
      out.write("                    <div class=\"fotorama__arr fotorama__arr--next\" tabindex=\"0\" role=\"button\"></div>\r\n");
      out.write("                    <div class=\"fotorama__vidio-close\"></div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"fotorama__nav-wrap\">\r\n");
      out.write("                    <div class=\"fotorama__nav fotorama__nav--thumbs fotorama__shadows--right\" style=\"width: 579px;\">\r\n");
      out.write("                        <div class=\"fotorama__nav__shaft fotorama__grab\" style=\"transition-duration: 0ms; transform: translate3d(0px, 0px, 0px);\">\r\n");
      out.write("                            <div class=\"fotorama__thumb-border\" style=\"transition-duration: 0ms; transform: translate3d(66px, 0px, 0px); width: 60px;\"></div>\r\n");
      out.write("                            <div class=\"fotorama__nav__frame fotorama__nav__frame--thumb\" tabindex=\"0\" role=\"button\" style=\"width: 64px;\"></div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div ng-controller=\"mp20_gallery_controller\" class=\"ng-scope\">\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"black_screen\"></div>\r\n");
      out.write("\r\n");
      out.write("    ");
      out.write("\n");
      out.write("\n");
      out.write("    <footer>\n");
      out.write("        <div id=\"footer\">\n");
      out.write("            <div class=\"inner__Copy\">\n");
      out.write("                <h2 class=\"screen_out\">서비스 이용정보</h2>\n");
      out.write("                <div class=\"info_service\">\n");
      out.write("                    <a href=\"#\" class=\"link_service link_company\">회사소개</a>\n");
      out.write("                    <a href=\"#\" class=\"link_service link_service2\">개인정보처리방침</a>\n");
      out.write("                    <a href=\"#\" class=\"link_service link_service2\">광고/제휴문의</a>\n");
      out.write("                </div>\n");
      out.write("​\n");
      out.write("                <div class=\"copyrights\">\n");
      out.write("                    <small>\n");
      out.write("                        <span class=\"txt_copy\">㈜left34</span>\n");
      out.write("                        <span class=\"txt_copy\">서울특별시 강남구 역삼동</span>\n");
      out.write("                        <span class=\"txt_copy\">대표이사: JEON HEE JIN(전희진)</span>\n");
      out.write("                        <span class=\"txt_copy\">사업자 등록번호: 219-12-18109</span>\n");
      out.write("                        <span class=\"txt_copy\">통신판매업 신고번호: 219-12-18109</span>\n");
      out.write("                        <span class=\"txt_copy\">고객센터: 02-1234-5678</span>\n");
      out.write("                        <span class=\"copyright\">© 2019 Eat's Twelve Co., Ltd. All rights reserved.</span>\n");
      out.write("                    </small>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </footer>    \n");
      out.write("</body>\n");
      out.write("</html>   ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
